"""initial state

Revision ID: 0f51d3e61114
Revises: 
Create Date: 2019-07-02 19:01:50.091684

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '0f51d3e61114'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_variants',
    sa.Column('id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('product_id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('created', sa.DATETIME(), nullable=True),
    sa.Column('last_updated', sa.DATETIME(), nullable=True),
    sa.Column('in_stock', sa.BOOLEAN(), nullable=True),
    sa.Column('specifications', sqlite.JSON(), nullable=True),
    sa.Column('list_price', sa.NUMERIC(), nullable=True),
    sa.Column('price', sa.NUMERIC(), nullable=True),
    sa.Column('price_per_gram', sa.NUMERIC(), nullable=True),
    sa.CheckConstraint('in_stock IN (0, 1)'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id', 'product_id')
    )
    op.create_table('products',
    sa.Column('id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('created', sa.DATETIME(), nullable=True),
    sa.Column('last_updated', sa.DATETIME(), nullable=True),
    sa.Column('title', sa.VARCHAR(), nullable=True),
    sa.Column('url', sa.VARCHAR(), nullable=False),
    sa.Column('in_stock', sa.BOOLEAN(), nullable=True),
    sa.Column('brand', sa.VARCHAR(), nullable=True),
    sa.CheckConstraint('in_stock IN (0, 1)'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('triggers',
    sa.Column('username', sa.VARCHAR(), nullable=False),
    sa.Column('keyword', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('username', 'keyword')
    )
    op.create_table('product_history',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('product_id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('variant_id', sa.INTEGER(), nullable=False),
    sa.Column('event', sa.VARCHAR(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_history')
    op.drop_table('triggers')
    op.drop_table('products')
    op.drop_table('product_variants')
    # ### end Alembic commands ###
